[project]
name = "pythonwa-default-layer"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
  "pydantic~=2.10",
  "requests~=2.32",
  "aws-lambda-typing~=2.20",
]
