exclude: '^$'
fail_fast: false
repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.7.0
    hooks:
    -   id: pre-commit-update
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: fix-byte-order-marker
    -   id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
    -   id: mixed-line-ending
        args: ["--fix=lf"]
    -   id: end-of-file-fixer
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: detect-private-key
    -   id: detect-aws-credentials
        args: ['--allow-missing-credentials']
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix', '--indent', '2', '--no-sort-keys']
        exclude: ^Pipfile
    -   id: check-yaml
        exclude: ^charts/
    -   id: check-toml

# commit messages
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.7.1
    hooks:
    -   id: commitizen
        stages: [commit-msg]

# Terraform
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate
  #   -   id: terraform_docs_replace
    -   id: terraform_tflint
        args: ['--args=--disable-rule=terraform_unused_declarations']
    -   id: terraform_tfsec

# Python tools
-   repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.11.10
    hooks:
    # Run the linter.
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
    # Run the formatter.
    -   id: ruff-format

# Shell script tools
-   repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: v2.2.0
    hooks:
    -   id: shell-fmt-go
        args:
        -   -i
        -   "2"

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck
